version: '3.9'

services:
  dc-slot-booking_api:
    build: ./api
    volumes:
      - ./api:/usr/local/api
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    environment:
      MONGO_HOST: dc-slot-booking_mongodb
      MONGO_USER: admin
      MONGO_PASS: admin
    ports:
      - "8000:8000"
      - "4444:4444"  # rpdb port for debugging.
    networks:
      - dc-slot-booking_network
    depends_on:
      - dc-slot-booking_mongodb

  dc-slot-booking_mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_ROOT_DATABASE=admin
    volumes:
      - dc-slot-booking_volume_mongodb:/data/db
    networks:
      - dc-slot-booking_network

  dc-slot-booking_front:
    build: ./front
    volumes:
      - ./front:/usr/local/front
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    networks:
      - dc-slot-booking_network
    depends_on:
      - dc-slot-booking_api

volumes:
  dc-slot-booking_volume_mongodb:
networks:
  dc-slot-booking_network:
    name: dc-slot-booking_network
    driver: bridge
